### ISSUE TITLE
运行 bash script/run.sh出现错误

### ISSUE THREAD

**Issue by kplxwb** [zjukg/Structure-CLIP#16]
Some weights of BertModel were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['bert.linear.bias', 'bert.linear.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                                                                                    | 0/771 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/fgw/Structure-CLIP/model/train.py", line 61, in <module>
    for i, batch in enumerate(tqdm(train_vg_dataloader, total=len(train_vg_dataloader))):
  File "/root/anaconda3/envs/str/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/str/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/str/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/str/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/str/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/str/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/root/anaconda3/envs/str/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/str/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/fgw/Structure-CLIP/model/dataloader_downstream.py", line 195, in __getitem__
    image = Image.open(scene["image_path"]).convert('RGB')
  File "/root/anaconda3/envs/str/lib/python3.10/site-packages/PIL/Image.py", line 3277, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/data/coco_data/train2014/COCO_train2014_000000431077.jpg'
按照您的要求配置好环境后运行了,其中还创建了一个wandb账户,但是出现了如下错误，希望您的实验步骤和需要哪些模型能写的更详细点

**Comment by kplxwb** [comment]
解决了，是没有图片数据的缘故

**Comment by lichong0** [comment]
老师您好，请问您数据集下载了吗，原文链接失效了

**Comment by kplxwb** [comment]
给个邮箱，我只有这个json_data,可以发给你

**Comment by lichong0** [comment]
lc18663217538@163.com 谢谢您
